Train:
  batch_size: 128
  learning_rate: 0.01
  reg: 0.005
  epochs: 10
  steps: [6, 8]
  warmup: 0
  momentum: 0.9
  gamma: 1

network:
  model: ResNet-32 # TwoLayerNet or VanillaCNN or MyModel or ResNet-32
  save_best: True

data:
  imbalance: imbalance # regular or imbalance
  beta: 0.5

loss:
  loss_type: Focal # CE or Focal
